FROM debian 
ENV GITHUB_API_TOKEN xxxx
LABEL maintainer="fazzani.heni@outlook.com" \
      description="debian image with préinstalled xmltv_util package" \
      system.dist="linux" \
	  multi.name="xmltv_util"

WORKDIR /work

RUN set -ex
RUN apt-get update -yqq \
    && apt-get upgrade -yqq \
    && apt-get install -yqq --no-install-recommends \
       xmltv-util \
       dos2unix zip \
    && apt-get autoremove -yqq --purge \
    && apt-get clean \
    && rm -rf \
       /var/lib/apt/lists/* \
       /tmp/* \
       /var/tmp/* \
       /usr/share/man \
       /usr/share/doc \
       /usr/share/doc-base

CMD [ "/bin/bash" ]